In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('soccer_international_history_dataset.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
# Send only the first column to onehotencoder
X_oneHotEncoded = onehotencoder.fit_transform(x[:, [0]]).toarray()
X_oneHotEncoded1 = onehotencoder.fit_transform(x[:, [1]]).toarray()
X_oneHotEncoded2 = onehotencoder.fit_transform(x[:, [2]]).toarray()
x = np.hstack((X_oneHotEncoded, X_oneHotEncoded1, X_oneHotEncoded2))

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.002584981, random_state = 0)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 0]
 [2 1]
 [1 2]
 [1 1]
 [2 0]
 [2 2]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [2 0]
 [2 2]
 [2 2]
 [0 2]
 [2 0]
 [1 1]
 [2 2]
 [2 2]
 [1 2]
 [2 2]
 [2 2]
 [1 0]
 [2 1]
 [2 0]
 [2 2]
 [2 0]
 [2 0]
 [2 1]
 [1 1]
 [2 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [2 2]
 [1 2]
 [1 0]
 [2 2]
 [2 1]
 [2 2]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [2 1]
 [2 1]
 [2 2]
 [1 1]
 [2 0]
 [2 2]
 [2 1]
 [2 1]
 [1 1]
 [1 1]
 [0 1]
 [2 1]
 [2 2]
 [2 2]
 [1 2]
 [2 2]
 [2 0]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 1]
 [2 0]
 [2 2]
 [2 2]
 [0 0]
 [2 1]
 [2 2]
 [1 2]
 [2 2]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [0 2]
 [2 2]
 [2 2]
 [2 2]
 [1 2]
 [2 2]
 [1 2]
 [0 0]
 [0 2]
 [2 0]
 [1 1]
 [2 2]
 [1 0]
 [1 1]
 [2 0]
 [1 1]
 [2 2]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 3  5 13]
 [ 2 17 12]
 [ 3  9 36]]


0.56